const tamil=Number(prompt("Enter The Tamil Marks:"))
const eng=Number(prompt("Enter The English Marks:"))
const maths=Number(prompt("Enter The Maths Marks:"))
const physics=Number(prompt("Enter The Physics Marks:"))
const Chemistry=Number(prompt("Enter The Chemistry Marks:"))
const Cs=Number(prompt("Enter The Computer Science Marks:"))
let cutoff=maths+(physics/2)+(Chemistry/2)
document.write(" Tamil: "+tamil+"<br>")
document.write(" English: "+eng+"<br>")
document.write(" Maths: "+maths+"<br>")
document.write(" Physics: "+physics+"<br>")
document.write(" Chemistry: "+Chemistry+"<br>")
document.write(" Computer Science: "+Cs+"<br>")
document.write(" Total Cutoff Mark: "+cutoff)
